[project]
name = "bitbibliotek"
version = "0.1"
description = "Til opbevaring a bits"
dependencies = [
    "flask",
    "python-dotenv",
    "gunicorn",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
